2020-12-07 14:16:14,083 ERROR: Exception on / [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\main\routes.py", line 9, in index
    return render_template('index.html')
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\base.html", line 8, in block "navbar"
    {% include '_nav.html' %}
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\_nav.html", line 11, in top-level template code
    <li><a href="{{ url_for(main.index) }}">Start vragenlijst</a></li>
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'main' is undefined
2020-12-07 14:16:14,083 ERROR: Exception on / [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\main\routes.py", line 9, in index
    return render_template('index.html')
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\base.html", line 8, in block "navbar"
    {% include '_nav.html' %}
  File "D:\Documenten\Projects\DataEnWatNu\src\templates\_nav.html", line 11, in top-level template code
    <li><a href="{{ url_for(main.index) }}">Start vragenlijst</a></li>
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'main' is undefined
2020-12-07 14:37:40,242 ERROR: Exception on /questionlist/question [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/question]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 8, in question
    return redirect(url_for('main.index'))
NameError: name 'redirect' is not defined
2020-12-07 14:37:40,242 ERROR: Exception on /questionlist/question [GET] [in D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py:1891] - [from 127.0.0.1 to http://127.0.0.1:5000/questionlist/question]
Traceback (most recent call last):
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Documenten\Projects\DataEnWatNu\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Documenten\Projects\DataEnWatNu\src\blueprints\questions\routes.py", line 8, in question
    return redirect(url_for('main.index'))
NameError: name 'redirect' is not defined
